---
services:
  traefik:
    volumes:
      - "./etc/local:/etc/traefik"
    labels:
      - "traefik.http.routers.traefik.entrypoints=web"

      # # require authentication to access the dashboard (uncomment the next lines to enable)
      # - "traefik.http.routers.traefik.middlewares=auth"
      #
      # use `mkpasswd --method=bcrypt` to convert your password to a bcrypt
      # hash before pasting it here. (make sure to double up any dollar sign
      # symbols ($ -> $$) since the dollar sign symbol is used as an escape
      # character in YAML)
      # - "traefik.http.middlewares.auth.basicauth.users=admin:${TRAEFIK_DASHBOARD_PASSWORD_HASH:-$$2b$$05$$v2kiZzxQVEouDNeILmzUTeJBE2ScPBJgfKagbLQSDD3fqJtg6.6VW}"
